"""Lock Python 3.13 Linux amd64 wheels for the backend checks image."""

import argparse
import json
import subprocess
import sys
import tempfile
from pathlib import Path


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--report", type=Path, help="Reuse a pip installation report")
    args = parser.parse_args()
    root = Path(__file__).resolve().parents[3]
    with tempfile.TemporaryDirectory() as temporary:
        report = args.report or Path(temporary) / "report.json"
        if args.report is None:
            subprocess.run(
                [
                    sys.executable,
                    "-m",
                    "pip",
                    "install",
                    "--dry-run",
                    "--ignore-installed",
                    "--only-binary=:all:",
                    "--platform=manylinux_2_28_x86_64",
                    "--platform=manylinux2014_x86_64",
                    "--python-version=3.13",
                    "--implementation=cp",
                    "--abi=cp313",
                    "--report",
                    str(report),
                    "-r",
                    str(root / "backend/requirements-dev.txt"),
                ],
                check=True,
            )
        packages = json.loads(report.read_text(encoding="utf-8"))["install"]
        lines = [
            "# Generated by lock_dependencies.py; Python 3.13, Linux amd64.",
            "# Source versions: backend/requirements-dev.txt. Wheels only.",
        ]
        packages.sort(key=lambda item: item["metadata"]["name"].lower())
        for package in packages:
            download = package["download_info"]
            if not download["url"].endswith(".whl"):
                raise ValueError("The dependency report must contain only wheels")
            digest = download["archive_info"]["hashes"]["sha256"]
            metadata = package["metadata"]
            lines.append(
                f"{metadata['name']}=={metadata['version']} --hash=sha256:{digest}"
            )
        Path(__file__).with_name("requirements.lock").write_text(
            "\n".join(lines) + "\n", encoding="utf-8"
        )


if __name__ == "__main__":
    main()
