"""Lock Python 3.13 Linux amd64 wheels for the backend checks image."""

import json
import subprocess
import tempfile
from pathlib import Path


def main() -> None:
    root = Path(__file__).resolve().parents[3]
    with tempfile.TemporaryDirectory() as temporary:
        report = Path(temporary) / "report.json"
        # pip --platform selects wheels but still evaluates dependency markers
        # on the host OS. Resolve inside the same Linux image as backend-checks.
        subprocess.run(
            [
                "docker",
                "run",
                "--rm",
                "--pull=always",
                "--platform=linux/amd64",
                "--mount",
                f"type=bind,source={root},target=/workspace,readonly",
                "--mount",
                f"type=bind,source={temporary},target=/lock",
                "python:3.13-slim",
                "python",
                "-m",
                "pip",
                "install",
                "--dry-run",
                "--ignore-installed",
                "--only-binary=:all:",
                "--report=/lock/report.json",
                "-r",
                "/workspace/backend/requirements-dev.txt",
            ],
            check=True,
        )
        packages = json.loads(report.read_text(encoding="utf-8"))["install"]
        lines = [
            "# Generated by lock_dependencies.py; Python 3.13, Linux amd64.",
            "# Source versions: backend/requirements-dev.txt. Wheels only.",
        ]
        packages.sort(key=lambda item: item["metadata"]["name"].lower())
        for package in packages:
            download = package["download_info"]
            if not download["url"].endswith(".whl"):
                raise ValueError("The dependency report must contain only wheels")
            digest = download["archive_info"]["hashes"]["sha256"]
            metadata = package["metadata"]
            lines.append(
                f"{metadata['name']}=={metadata['version']} --hash=sha256:{digest}"
            )
        Path(__file__).with_name("requirements.lock").write_text(
            "\n".join(lines) + "\n", encoding="utf-8"
        )


if __name__ == "__main__":
    main()
