import 'package:flutter/material.dart';

const managementLabels = <String, String>{
  'name': 'Tên',
  'account_type': 'Loại tài khoản',
  'balance': 'Số dư',
  'currency': 'Tiền tệ',
  'icon': 'Biểu tượng',
  'color': 'Màu sắc',
  'account_number': 'Số tài khoản / thẻ',
  'institution_name': 'Ngân hàng / tổ chức',
  'credit_limit': 'Hạn mức tín dụng',
  'statement_day': 'Ngày chốt sao kê',
  'payment_due_day': 'Ngày đến hạn',
  'is_included_in_total': 'Tính vào tổng tài sản',
  'is_archived': 'Lưu trữ ví',
  'parent_id': 'Danh mục cha',
  'is_income': 'Danh mục thu nhập',
  'pillar': 'Trụ cột Kakeibo',
  'display_order': 'Thứ tự hiển thị',
  'transaction_id': 'Giao dịch',
  'tag_id': 'Thẻ',
  'category_id': 'Danh mục',
  'month_year': 'Tháng ngân sách',
  'limit_amount': 'Hạn mức',
  'alert_threshold_percent': 'Ngưỡng cảnh báo (%)',
  'account_id': 'Ví',
  'target_amount': 'Số tiền mục tiêu',
  'current_amount': 'Đã tiết kiệm',
  'target_date': 'Ngày mục tiêu',
  'status': 'Trạng thái',
  'notes': 'Ghi chú',
  'type': 'Loại khoản nợ',
  'person_name': 'Người / tổ chức',
  'phone_number': 'Số điện thoại',
  'amount': 'Số tiền',
  'paid_amount': 'Đã thanh toán',
  'due_date': 'Hạn thanh toán',
  'interest_rate': 'Lãi suất (% / năm)',
  'transaction_type': 'Loại giao dịch',
  'description': 'Mô tả',
  'frequency': 'Chu kỳ',
  'start_date': 'Ngày bắt đầu',
  'end_date': 'Ngày kết thúc',
  'next_execution_date': 'Ngày thực hiện tiếp theo',
  'auto_create': 'Tự tạo khi đến hạn',
  'is_active': 'Đang hoạt động',
  'forecast_date': 'Ngày dự báo',
  'predicted_balance': 'Số dư dự báo',
  'predicted_income': 'Thu nhập dự báo',
  'predicted_expense': 'Chi tiêu dự báo',
  'lower_bound': 'Cận dưới',
  'upper_bound': 'Cận trên',
  'risk_level': 'Mức rủi ro',
  'model_name': 'Mô hình',
  'alert_type': 'Loại cảnh báo',
  'severity': 'Mức độ',
  'title': 'Tiêu đề',
  'message': 'Nội dung',
  'predicted_deficit_date': 'Ngày thiếu hụt dự báo',
  'predicted_deficit_amount': 'Số tiền thiếu hụt',
  'suggested_action': 'Đề xuất',
  'is_read': 'Đã đọc',
  'is_resolved': 'Đã xử lý',
  'user_query': 'Câu hỏi',
  'context_summary': 'Bối cảnh tư vấn',
  'ai_recommendation': 'Nội dung tư vấn',
  'session_id': 'Cuộc trò chuyện',
  'sender': 'Người gửi',
  'content': 'Tin nhắn',
  'context_snapshot': 'Bối cảnh tin nhắn',
  'full_name': 'Họ tên',
  'avatar_url': 'Đường dẫn ảnh đại diện',
  'payroll_day': 'Ngày nhận lương',
  'monthly_savings_target': 'Mục tiêu tiết kiệm mỗi tháng',
  'reminder_time': 'Giờ nhắc nhở',
  'biometrics_enabled': 'Sinh trắc học',
  'dark_mode_enabled': 'Chế độ tối',
  'current_balance': 'Số dư hiện tại',
  'monthly_income': 'Thu nhập tháng',
  'monthly_expense': 'Chi tiêu tháng',
  'burn_rate': 'Mức chi tiêu mỗi ngày',
  'days_to_payroll': 'Số ngày tới kỳ lương',
};
const managementChoices = <String, String>{
  'cash': 'Tiền mặt',
  'bank': 'Ngân hàng',
  'e_wallet': 'Ví điện tử',
  'credit_card': 'Thẻ tín dụng',
  'investment': 'Đầu tư',
  'savings': 'Tiết kiệm',
  'needs': 'Thiết yếu',
  'wants': 'Mong muốn',
  'culture': 'Văn hóa',
  'unexpected': 'Dự phòng',
  'income': 'Thu nhập',
  'expense': 'Chi tiêu',
  'in_progress': 'Đang thực hiện',
  'completed': 'Hoàn thành',
  'cancelled': 'Đã hủy',
  'debt': 'Đi vay',
  'loan': 'Cho vay',
  'pending': 'Chưa thanh toán',
  'partial': 'Thanh toán một phần',
  'paid': 'Đã thanh toán',
  'overdue': 'Quá hạn',
  'daily': 'Hàng ngày',
  'weekly': 'Hàng tuần',
  'biweekly': 'Hai tuần',
  'monthly': 'Hàng tháng',
  'quarterly': 'Hàng quý',
  'yearly': 'Hàng năm',
  'safe': 'An toàn',
  'warning': 'Cảnh báo',
  'danger': 'Nguy hiểm',
  'info': 'Thông tin',
  'critical': 'Nghiêm trọng',
  'deficit_risk': 'Nguy cơ thiếu hụt',
  'budget_exceeded': 'Vượt ngân sách',
  'unusual_expense': 'Chi tiêu bất thường',
  'low_balance': 'Số dư thấp',
  'bill_due': 'Hóa đơn đến hạn',
  'user': 'Bạn',
  'assistant': 'Trợ lý',
  'system': 'Hệ thống',
};
const managementRelations = <String, String>{
  'account_id': 'accounts',
  'category_id': 'categories',
  'parent_id': 'categories',
  'transaction_id': 'transactions',
  'tag_id': 'tags',
  'session_id': 'ai_chat_sessions',
};

const managementModuleGroups = {
  'Thu chi và tài khoản': ['accounts', 'recurring_transactions', 'debts_loans'],
  'Ngân sách và tiết kiệm': ['budgets', 'saving_goals'],
  'Danh mục và thẻ': ['categories', 'tags', 'transaction_tags'],
  'Dự báo và tư vấn': [
    'cashflow_forecasts',
    'cashflow_alerts',
    'ai_consultations',
    'ai_chat_sessions',
    'ai_chat_messages',
  ],
  'Cá nhân': ['profile'],
};

const managementModuleIcons = <String, IconData>{
  'accounts': Icons.account_balance_wallet_outlined,
  'categories': Icons.category_outlined,
  'tags': Icons.sell_outlined,
  'transaction_tags': Icons.label_outline,
  'budgets': Icons.pie_chart_outline,
  'saving_goals': Icons.savings_outlined,
  'debts_loans': Icons.handshake_outlined,
  'recurring_transactions': Icons.event_repeat,
  'cashflow_forecasts': Icons.trending_up,
  'cashflow_alerts': Icons.notifications_outlined,
  'ai_consultations': Icons.lightbulb_outline,
  'ai_chat_sessions': Icons.forum_outlined,
  'ai_chat_messages': Icons.chat_bubble_outline,
  'profile': Icons.person_outline,
};

const managementCreateLabels = {
  'accounts': 'Thêm ví',
  'categories': 'Thêm danh mục',
  'tags': 'Thêm thẻ',
  'transaction_tags': 'Gắn thẻ',
  'budgets': 'Thêm ngân sách',
  'saving_goals': 'Thêm mục tiêu',
  'debts_loans': 'Thêm khoản nợ / vay',
  'recurring_transactions': 'Thêm lịch thu chi',
};

const managementAppearanceIcons = <String, IconData>{
  'account_balance_wallet': Icons.account_balance_wallet_outlined,
  'account_balance': Icons.account_balance_outlined,
  'payments': Icons.payments_outlined,
  'credit_card': Icons.credit_card,
  'savings': Icons.savings_outlined,
  'category': Icons.category_outlined,
  'restaurant': Icons.restaurant_outlined,
  'shopping_bag': Icons.shopping_bag_outlined,
  'directions_car': Icons.directions_car_outlined,
  'home': Icons.home_outlined,
  'school': Icons.school_outlined,
  'favorite': Icons.favorite_outline,
};

const managementIconLabels = {
  'account_balance_wallet': 'Ví',
  'account_balance': 'Ngân hàng',
  'payments': 'Tiền mặt',
  'credit_card': 'Thẻ tín dụng',
  'savings': 'Tiết kiệm',
  'category': 'Danh mục',
  'restaurant': 'Ăn uống',
  'shopping_bag': 'Mua sắm',
  'directions_car': 'Di chuyển',
  'home': 'Nhà ở',
  'school': 'Học tập',
  'favorite': 'Sức khỏe',
};

const managementMoneyFields = {
  'balance',
  'amount',
  'credit_limit',
  'limit_amount',
  'target_amount',
  'current_amount',
  'paid_amount',
  'predicted_balance',
  'predicted_income',
  'predicted_expense',
  'lower_bound',
  'upper_bound',
  'predicted_deficit_amount',
  'monthly_savings_target',
};

String recordCaption(Map<String, dynamic> item) {
  for (final field in [
    'name',
    'title',
    'person_name',
    'description',
    'clean_description',
    'raw_description',
    'user_query',
    'content',
    'full_name',
    'email',
    'forecast_date',
    'month_year',
  ]) {
    if (item[field] != null && '${item[field]}'.isNotEmpty) {
      return '${item[field]}';
    }
  }
  if (item.containsKey('transaction_id')) {
    return 'Giao dịch #${item['transaction_id']} · Thẻ #${item['tag_id']}';
  }
  return 'Bản ghi #${item['id']}';
}
